version: "3.8"
services:

  friends_service_tests:
    build:
      context: ./friends_service
      dockerfile: docker/DockerfileTests
    env_file:
      - ./friends_service/env/test.env
    volumes:
      - "./friends_service:/friends_service"
    depends_on:
      - postgres_tests
      - redis_tests

  postgres_tests:
    image: postgres:13
    env_file:
      - ./friends_service/env/test.env

  redis_tests:
    image: redis:latest

  friends_service:
    build:
      context: ./friends_service
      dockerfile: docker/Dockerfile
    ports:
      - "5057:5057"
    env_file:
      - ./friends_service/env/dev.env
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:13
    env_file:
      - ./friends_service/env/dev.env

  redis:
    image: redis:latest
    command: ["redis-server", "--maxmemory", "200mb", "--maxmemory-policy", "allkeys-lru"]
