version: "3.8"
services:

  friends_service_tests:
    build:
      context: ./friends_service
      dockerfile: DockerfileTests
    env_file:
      - ./friends_service/docker-compose-test.env
    volumes:
      - "./friends_service:/friends_service"
    depends_on:
      postgres_tests:
        condition: service_healthy
    links:
      - postgres_tests

  postgres_tests:
    image: postgres:13
    env_file:
      - ./friends_service/docker-compose-test.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres_tests"]
      interval: 5s
      timeout: 5s
      retries: 5

  friends_service:
    build:
      context: ./friends_service
      dockerfile: Dockerfile
    ports:
      - "5057:5057"
    env_file:
      - ./friends_service/docker-compose.env
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres

  postgres:
    image: postgres:13
    env_file:
      - ./friends_service/docker-compose.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5