version: "3.8"
services:

  friends_service_tests:
    build:
      context: ./friends_service
      dockerfile: DockerfileTests
    env_file:
      - ./friends_service/docker-compose-test.env
    volumes:
      - "./friends_service:/app"
    depends_on:
      - postgres_tests

  postgres_tests:
    image: postgres:13
    environment:
      - ./friends_service/docker-compose-test.env

  friends_service:
    build:
      context: ./friends_service
      dockerfile: Dockerfile
    ports:
      - "5057:5057"
    env_file:
      - ./friends_service/docker-compose.env
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      - ./friends_service/docker-compose.env